### ISSUE TITLE
Why to use django-cte-trees over treebeard

### ISSUE THREAD

**Issue by cancan101** [petrounias/django-cte-trees#2]
There is discussion of when NOT to use `django-cte-trees`, but what are the advantages of `django-cte-trees` over `treebeard` or `django-mptt`? 

It looks like treebeard currently has three modes of operation: https://tabo.pe/projects/django-treebeard/docs/1.60/api.html

**Comment by matthiask** [comment]
The biggest advantage is that corrupted trees are not possible with cte-trees because no information is duplicated as is the case with the implementation of nested sets and materialized paths in treebeard and mptt.

They are not possible with treebeard's AL_Node either, but the performance will be worse with AL_Node if you're doing queries on the tree structure.

Of course the downside is that the _implementation_ of django-cte-tree only supports PostgreSQL right now (some other databases also support recursive queries, but support isn't implemented right now)
